services:
  rabbitmq:
      image: rabbitmq:management
      env_file:
        - ./.env
      container_name: rabbitmq
      ports:
        - "${RABBITMQ_NODE_PORT_EXTERNAL:-5672}:${RABBITMQ_NODE_PORT:-5672}" # RabbitMQ default port
        - "${RABBITMQ_MNGMNT_PORT_EXTERNAL:-15672}:15672" # RabbitMQ management plugin port
      environment:
        RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER:-guest}"
        RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS:-guest}"
      healthcheck:
        test: >
          rabbitmq-diagnostics check_port_connectivity
        interval: 5s
        timeout: 5s
        retries: 12
  php:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: symfony server:start --no-tls --allow-all-ip --no-interaction

  db:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: docker/db/Dockerfile
      args:
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}

  pgadmin:
    env_file:
      - ./.env
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"

  node:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend/react:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"