<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250331161715 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE admins (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, id_user INT NOT NULL, id_role INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_A2E0150F6B3CA4B ON admins (id_user)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_A2E0150FDC499668 ON admins (id_role)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE authors (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, author VARCHAR(255) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE book_authors (id_book INT NOT NULL, id_author INT NOT NULL, PRIMARY KEY(id_book, id_author))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_1D2C02C740C5BF33 ON book_authors (id_book)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_1D2C02C79B986D25 ON book_authors (id_author)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE book_genres (id_book INT NOT NULL, id_genre INT NOT NULL, PRIMARY KEY(id_book, id_genre))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_813CEE9B40C5BF33 ON book_genres (id_book)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_813CEE9B6DD572C8 ON book_genres (id_genre)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE book_tags (id_book INT NOT NULL, id_tag INT NOT NULL, PRIMARY KEY(id_book, id_tag))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_7621DF2E40C5BF33 ON book_tags (id_book)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_7621DF2E9D2D5FD9 ON book_tags (id_tag)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE books (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, cover VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX books_title_description_key ON books (title, description)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE comments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, comment VARCHAR(255) NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT 'NOW()' NOT NULL, id_user INT NOT NULL, id_book INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_5F9E962A6B3CA4B ON comments (id_user)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_5F9E962A40C5BF33 ON comments (id_book)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE genres (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, genre VARCHAR(100) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX genres_genre_key ON genres (genre)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE roles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(100) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX roles_role_key ON roles (role)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE sessions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, session_token VARCHAR(255) NOT NULL, expiration_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id_user INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_9A609D136B3CA4B ON sessions (id_user)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX sessions_session_token_key ON sessions (session_token)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE tags (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tag VARCHAR(100) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX tags_tag_key ON tags (tag)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL, hashed_password VARCHAR(100) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX users_username_key ON users (username)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX users_email_key ON users (email)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE admins ADD CONSTRAINT FK_A2E0150F6B3CA4B FOREIGN KEY (id_user) REFERENCES users (id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE admins ADD CONSTRAINT FK_A2E0150FDC499668 FOREIGN KEY (id_role) REFERENCES roles (id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE book_authors ADD CONSTRAINT FK_1D2C02C740C5BF33 FOREIGN KEY (id_book) REFERENCES books (id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE book_authors ADD CONSTRAINT FK_1D2C02C79B986D25 FOREIGN KEY (id_author) REFERENCES authors (id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE book_genres ADD CONSTRAINT FK_813CEE9B40C5BF33 FOREIGN KEY (id_book) REFERENCES books (id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE book_genres ADD CONSTRAINT FK_813CEE9B6DD572C8 FOREIGN KEY (id_genre) REFERENCES genres (id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE book_tags ADD CONSTRAINT FK_7621DF2E40C5BF33 FOREIGN KEY (id_book) REFERENCES books (id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE book_tags ADD CONSTRAINT FK_7621DF2E9D2D5FD9 FOREIGN KEY (id_tag) REFERENCES tags (id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE comments ADD CONSTRAINT FK_5F9E962A6B3CA4B FOREIGN KEY (id_user) REFERENCES users (id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE comments ADD CONSTRAINT FK_5F9E962A40C5BF33 FOREIGN KEY (id_book) REFERENCES books (id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE sessions ADD CONSTRAINT FK_9A609D136B3CA4B FOREIGN KEY (id_user) REFERENCES users (id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE admins DROP CONSTRAINT FK_A2E0150F6B3CA4B
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE admins DROP CONSTRAINT FK_A2E0150FDC499668
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE book_authors DROP CONSTRAINT FK_1D2C02C740C5BF33
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE book_authors DROP CONSTRAINT FK_1D2C02C79B986D25
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE book_genres DROP CONSTRAINT FK_813CEE9B40C5BF33
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE book_genres DROP CONSTRAINT FK_813CEE9B6DD572C8
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE book_tags DROP CONSTRAINT FK_7621DF2E40C5BF33
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE book_tags DROP CONSTRAINT FK_7621DF2E9D2D5FD9
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE comments DROP CONSTRAINT FK_5F9E962A6B3CA4B
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE comments DROP CONSTRAINT FK_5F9E962A40C5BF33
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE sessions DROP CONSTRAINT FK_9A609D136B3CA4B
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE admins
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE authors
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE book_authors
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE book_genres
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE book_tags
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE books
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE comments
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE genres
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE roles
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE sessions
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE tags
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE users
        SQL);
    }
}
