<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250428205706 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE admins DROP CONSTRAINT FK_A2E0150F6B3CA4B
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE admins ADD CONSTRAINT FK_A2E0150F6B3CA4B FOREIGN KEY (id_user) REFERENCES "user" (id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE comments DROP CONSTRAINT FK_5F9E962A6B3CA4B
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE comments ADD CONSTRAINT FK_5F9E962A6B3CA4B FOREIGN KEY (id_user) REFERENCES "user" (id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE sessions DROP CONSTRAINT FK_9A609D136B3CA4B
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE sessions ADD CONSTRAINT FK_9A609D136B3CA4B FOREIGN KEY (id_user) REFERENCES "user" (id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE users
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL, hashed_password VARCHAR(100) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX users_username_key ON users (username)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX users_email_key ON users (email)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE comments DROP CONSTRAINT fk_5f9e962a6b3ca4b
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE comments ADD CONSTRAINT fk_5f9e962a6b3ca4b FOREIGN KEY (id_user) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE sessions DROP CONSTRAINT fk_9a609d136b3ca4b
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE sessions ADD CONSTRAINT fk_9a609d136b3ca4b FOREIGN KEY (id_user) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE admins DROP CONSTRAINT fk_a2e0150f6b3ca4b
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE admins ADD CONSTRAINT fk_a2e0150f6b3ca4b FOREIGN KEY (id_user) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }
}
